#Cole DiGregorio
#Pizza Wars
#so the -g was done by CJ during office hours bacause i was getting a very weird error that 4 other TAs could not identify what i was doing wrong so finally CJ was using -g to find out why and for some reason this itself fixed my problem. We both dont know why but i could not have done the rest of the project without them.
compile:
	make date
	make pizzaStore
	make pizzaWars
	g++ driver.cpp Date.o PizzaStore.o PizzaWars.o MysteryMachine.o -Wall -o battle.out -g
date:
	g++ Date.cpp -c -g 	
pizzaStore:
	g++ PizzaStore.cpp -c -g
pizzaWars:
	g++ PizzaWars.cpp -c -g
run:
	./battle.out
clean:
	rm *.out
edit:
	emacs Date.cpp
